% Auto-generated by cameraCalibrator app on 10-Apr-2018
%-------------------------------------------------------

path = 'G:\Code\tiller-counting\0410\';

% Define images to process
imageFileNames = cell(1, 8);
for i = 1: 8
    imageFileNames{i} = strcat(path, int2str(i), '.bmp');
end

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 20;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')

for i = 1: 8
    pic = imread(strcat(path, int2str(i), '.bmp'));
    out_pic = undistortImage(pic, cameraParams);
    imwrite(out_pic, strcat(path, 'undistImage', int2str(i), '.bmp'))
end

myCamParam = struct(cameraParams);
inMat = myCamParam.IntrinsicMatrix;
tranVecs = myCamParam.TranslationVectors;
rotVecs = myCamParam.RotationVectors;
rotMats = myCamParam.RotationMatrices;
save(strcat(path, 'inMat.mat'), 'inMat')
save(strcat(path, 'tranVecs.mat'), 'tranVecs')
save(strcat(path, 'rotVecs.mat'), 'rotVecs')
save(strcat(path, 'rotMats.mat'), 'rotMats')

undistImageFileNames = cell(1, 8);
for i = 1: 8
    undistImageFileNames{i} = strcat(path, 'undistImage', int2str(i), '.bmp');
end

[undistImagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(undistImageFileNames);
save(strcat(path, 'undistImagePoints.mat'), 'undistImagePoints')